/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as QuizSandboxRouteImport } from './routes/quiz-sandbox'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ProductsGlp1WeightLossRouteImport } from './routes/products/glp-1-weight-loss'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as ApiPrxWebhooksRouteImport } from './routes/api/prx/webhooks'
import { Route as ApiPrxProductsRouteImport } from './routes/api/prx/products'
import { Route as ApiPrxPatientsRouteImport } from './routes/api/prx/patients'
import { Route as ApiPrxOrdersRouteImport } from './routes/api/prx/orders'
import { Route as ApiPrxMeRouteImport } from './routes/api/prx/me'
import { Route as ApiPrxIntakeDynamicRouteImport } from './routes/api/prx/intake-dynamic'
import { Route as ApiPrxIntakeRouteImport } from './routes/api/prx/intake'
import { Route as ApiPrxHealthRouteImport } from './routes/api/prx/health'
import { Route as ApiPrxEncountersRouteImport } from './routes/api/prx/encounters'
import { Route as ApiPrxEncounterTypesRouteImport } from './routes/api/prx/encounter-types'
import { Route as ApiPrxCheckoutRouteImport } from './routes/api/prx/checkout'
import { Route as ApiPrxCatalogRouteImport } from './routes/api/prx/catalog'
import { Route as ApiPrxWebhooksEventTypesRouteImport } from './routes/api/prx/webhooks.event-types'
import { Route as ApiPrxOrdersOrderIdRouteImport } from './routes/api/prx/orders.$orderId'
import { Route as ApiPrxEncountersEncounterIdRouteImport } from './routes/api/prx/encounters.$encounterId'
import { Route as ApiPrxAuthMeRouteImport } from './routes/api/prx/auth.me'
import { Route as ApiPrxEncounterTypesEncounterTypeIdSchemaRouteImport } from './routes/api/prx/encounter-types.$encounterTypeId.schema'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSandboxRoute = QuizSandboxRouteImport.update({
  id: '/quiz-sandbox',
  path: '/quiz-sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsGlp1WeightLossRoute = ProductsGlp1WeightLossRouteImport.update({
  id: '/products/glp-1-weight-loss',
  path: '/products/glp-1-weight-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxWebhooksRoute = ApiPrxWebhooksRouteImport.update({
  id: '/api/prx/webhooks',
  path: '/api/prx/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxProductsRoute = ApiPrxProductsRouteImport.update({
  id: '/api/prx/products',
  path: '/api/prx/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxPatientsRoute = ApiPrxPatientsRouteImport.update({
  id: '/api/prx/patients',
  path: '/api/prx/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxOrdersRoute = ApiPrxOrdersRouteImport.update({
  id: '/api/prx/orders',
  path: '/api/prx/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxMeRoute = ApiPrxMeRouteImport.update({
  id: '/api/prx/me',
  path: '/api/prx/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxIntakeDynamicRoute = ApiPrxIntakeDynamicRouteImport.update({
  id: '/api/prx/intake-dynamic',
  path: '/api/prx/intake-dynamic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxIntakeRoute = ApiPrxIntakeRouteImport.update({
  id: '/api/prx/intake',
  path: '/api/prx/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxHealthRoute = ApiPrxHealthRouteImport.update({
  id: '/api/prx/health',
  path: '/api/prx/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxEncountersRoute = ApiPrxEncountersRouteImport.update({
  id: '/api/prx/encounters',
  path: '/api/prx/encounters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxEncounterTypesRoute = ApiPrxEncounterTypesRouteImport.update({
  id: '/api/prx/encounter-types',
  path: '/api/prx/encounter-types',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxCheckoutRoute = ApiPrxCheckoutRouteImport.update({
  id: '/api/prx/checkout',
  path: '/api/prx/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxCatalogRoute = ApiPrxCatalogRouteImport.update({
  id: '/api/prx/catalog',
  path: '/api/prx/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxWebhooksEventTypesRoute =
  ApiPrxWebhooksEventTypesRouteImport.update({
    id: '/event-types',
    path: '/event-types',
    getParentRoute: () => ApiPrxWebhooksRoute,
  } as any)
const ApiPrxOrdersOrderIdRoute = ApiPrxOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => ApiPrxOrdersRoute,
} as any)
const ApiPrxEncountersEncounterIdRoute =
  ApiPrxEncountersEncounterIdRouteImport.update({
    id: '/$encounterId',
    path: '/$encounterId',
    getParentRoute: () => ApiPrxEncountersRoute,
  } as any)
const ApiPrxAuthMeRoute = ApiPrxAuthMeRouteImport.update({
  id: '/api/prx/auth/me',
  path: '/api/prx/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrxEncounterTypesEncounterTypeIdSchemaRoute =
  ApiPrxEncounterTypesEncounterTypeIdSchemaRouteImport.update({
    id: '/$encounterTypeId/schema',
    path: '/$encounterTypeId/schema',
    getParentRoute: () => ApiPrxEncounterTypesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/privacy': typeof PrivacyRoute
  '/quiz-sandbox': typeof QuizSandboxRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/glp-1-weight-loss': typeof ProductsGlp1WeightLossRoute
  '/account/': typeof AccountIndexRoute
  '/api/prx/catalog': typeof ApiPrxCatalogRoute
  '/api/prx/checkout': typeof ApiPrxCheckoutRoute
  '/api/prx/encounter-types': typeof ApiPrxEncounterTypesRouteWithChildren
  '/api/prx/encounters': typeof ApiPrxEncountersRouteWithChildren
  '/api/prx/health': typeof ApiPrxHealthRoute
  '/api/prx/intake': typeof ApiPrxIntakeRoute
  '/api/prx/intake-dynamic': typeof ApiPrxIntakeDynamicRoute
  '/api/prx/me': typeof ApiPrxMeRoute
  '/api/prx/orders': typeof ApiPrxOrdersRouteWithChildren
  '/api/prx/patients': typeof ApiPrxPatientsRoute
  '/api/prx/products': typeof ApiPrxProductsRoute
  '/api/prx/webhooks': typeof ApiPrxWebhooksRouteWithChildren
  '/api/prx/auth/me': typeof ApiPrxAuthMeRoute
  '/api/prx/encounters/$encounterId': typeof ApiPrxEncountersEncounterIdRoute
  '/api/prx/orders/$orderId': typeof ApiPrxOrdersOrderIdRoute
  '/api/prx/webhooks/event-types': typeof ApiPrxWebhooksEventTypesRoute
  '/api/prx/encounter-types/$encounterTypeId/schema': typeof ApiPrxEncounterTypesEncounterTypeIdSchemaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/privacy': typeof PrivacyRoute
  '/quiz-sandbox': typeof QuizSandboxRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/glp-1-weight-loss': typeof ProductsGlp1WeightLossRoute
  '/account': typeof AccountIndexRoute
  '/api/prx/catalog': typeof ApiPrxCatalogRoute
  '/api/prx/checkout': typeof ApiPrxCheckoutRoute
  '/api/prx/encounter-types': typeof ApiPrxEncounterTypesRouteWithChildren
  '/api/prx/encounters': typeof ApiPrxEncountersRouteWithChildren
  '/api/prx/health': typeof ApiPrxHealthRoute
  '/api/prx/intake': typeof ApiPrxIntakeRoute
  '/api/prx/intake-dynamic': typeof ApiPrxIntakeDynamicRoute
  '/api/prx/me': typeof ApiPrxMeRoute
  '/api/prx/orders': typeof ApiPrxOrdersRouteWithChildren
  '/api/prx/patients': typeof ApiPrxPatientsRoute
  '/api/prx/products': typeof ApiPrxProductsRoute
  '/api/prx/webhooks': typeof ApiPrxWebhooksRouteWithChildren
  '/api/prx/auth/me': typeof ApiPrxAuthMeRoute
  '/api/prx/encounters/$encounterId': typeof ApiPrxEncountersEncounterIdRoute
  '/api/prx/orders/$orderId': typeof ApiPrxOrdersOrderIdRoute
  '/api/prx/webhooks/event-types': typeof ApiPrxWebhooksEventTypesRoute
  '/api/prx/encounter-types/$encounterTypeId/schema': typeof ApiPrxEncounterTypesEncounterTypeIdSchemaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/privacy': typeof PrivacyRoute
  '/quiz-sandbox': typeof QuizSandboxRoute
  '/terms': typeof TermsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/glp-1-weight-loss': typeof ProductsGlp1WeightLossRoute
  '/account/': typeof AccountIndexRoute
  '/api/prx/catalog': typeof ApiPrxCatalogRoute
  '/api/prx/checkout': typeof ApiPrxCheckoutRoute
  '/api/prx/encounter-types': typeof ApiPrxEncounterTypesRouteWithChildren
  '/api/prx/encounters': typeof ApiPrxEncountersRouteWithChildren
  '/api/prx/health': typeof ApiPrxHealthRoute
  '/api/prx/intake': typeof ApiPrxIntakeRoute
  '/api/prx/intake-dynamic': typeof ApiPrxIntakeDynamicRoute
  '/api/prx/me': typeof ApiPrxMeRoute
  '/api/prx/orders': typeof ApiPrxOrdersRouteWithChildren
  '/api/prx/patients': typeof ApiPrxPatientsRoute
  '/api/prx/products': typeof ApiPrxProductsRoute
  '/api/prx/webhooks': typeof ApiPrxWebhooksRouteWithChildren
  '/api/prx/auth/me': typeof ApiPrxAuthMeRoute
  '/api/prx/encounters/$encounterId': typeof ApiPrxEncountersEncounterIdRoute
  '/api/prx/orders/$orderId': typeof ApiPrxOrdersOrderIdRoute
  '/api/prx/webhooks/event-types': typeof ApiPrxWebhooksEventTypesRoute
  '/api/prx/encounter-types/$encounterTypeId/schema': typeof ApiPrxEncounterTypesEncounterTypeIdSchemaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/confirmation'
    | '/privacy'
    | '/quiz-sandbox'
    | '/terms'
    | '/category/$slug'
    | '/products/$slug'
    | '/products/glp-1-weight-loss'
    | '/account/'
    | '/api/prx/catalog'
    | '/api/prx/checkout'
    | '/api/prx/encounter-types'
    | '/api/prx/encounters'
    | '/api/prx/health'
    | '/api/prx/intake'
    | '/api/prx/intake-dynamic'
    | '/api/prx/me'
    | '/api/prx/orders'
    | '/api/prx/patients'
    | '/api/prx/products'
    | '/api/prx/webhooks'
    | '/api/prx/auth/me'
    | '/api/prx/encounters/$encounterId'
    | '/api/prx/orders/$orderId'
    | '/api/prx/webhooks/event-types'
    | '/api/prx/encounter-types/$encounterTypeId/schema'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/confirmation'
    | '/privacy'
    | '/quiz-sandbox'
    | '/terms'
    | '/category/$slug'
    | '/products/$slug'
    | '/products/glp-1-weight-loss'
    | '/account'
    | '/api/prx/catalog'
    | '/api/prx/checkout'
    | '/api/prx/encounter-types'
    | '/api/prx/encounters'
    | '/api/prx/health'
    | '/api/prx/intake'
    | '/api/prx/intake-dynamic'
    | '/api/prx/me'
    | '/api/prx/orders'
    | '/api/prx/patients'
    | '/api/prx/products'
    | '/api/prx/webhooks'
    | '/api/prx/auth/me'
    | '/api/prx/encounters/$encounterId'
    | '/api/prx/orders/$orderId'
    | '/api/prx/webhooks/event-types'
    | '/api/prx/encounter-types/$encounterTypeId/schema'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/checkout'
    | '/confirmation'
    | '/privacy'
    | '/quiz-sandbox'
    | '/terms'
    | '/category/$slug'
    | '/products/$slug'
    | '/products/glp-1-weight-loss'
    | '/account/'
    | '/api/prx/catalog'
    | '/api/prx/checkout'
    | '/api/prx/encounter-types'
    | '/api/prx/encounters'
    | '/api/prx/health'
    | '/api/prx/intake'
    | '/api/prx/intake-dynamic'
    | '/api/prx/me'
    | '/api/prx/orders'
    | '/api/prx/patients'
    | '/api/prx/products'
    | '/api/prx/webhooks'
    | '/api/prx/auth/me'
    | '/api/prx/encounters/$encounterId'
    | '/api/prx/orders/$orderId'
    | '/api/prx/webhooks/event-types'
    | '/api/prx/encounter-types/$encounterTypeId/schema'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfirmationRoute: typeof ConfirmationRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizSandboxRoute: typeof QuizSandboxRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsGlp1WeightLossRoute: typeof ProductsGlp1WeightLossRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ApiPrxCatalogRoute: typeof ApiPrxCatalogRoute
  ApiPrxCheckoutRoute: typeof ApiPrxCheckoutRoute
  ApiPrxEncounterTypesRoute: typeof ApiPrxEncounterTypesRouteWithChildren
  ApiPrxEncountersRoute: typeof ApiPrxEncountersRouteWithChildren
  ApiPrxHealthRoute: typeof ApiPrxHealthRoute
  ApiPrxIntakeRoute: typeof ApiPrxIntakeRoute
  ApiPrxIntakeDynamicRoute: typeof ApiPrxIntakeDynamicRoute
  ApiPrxMeRoute: typeof ApiPrxMeRoute
  ApiPrxOrdersRoute: typeof ApiPrxOrdersRouteWithChildren
  ApiPrxPatientsRoute: typeof ApiPrxPatientsRoute
  ApiPrxProductsRoute: typeof ApiPrxProductsRoute
  ApiPrxWebhooksRoute: typeof ApiPrxWebhooksRouteWithChildren
  ApiPrxAuthMeRoute: typeof ApiPrxAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-sandbox': {
      id: '/quiz-sandbox'
      path: '/quiz-sandbox'
      fullPath: '/quiz-sandbox'
      preLoaderRoute: typeof QuizSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/glp-1-weight-loss': {
      id: '/products/glp-1-weight-loss'
      path: '/products/glp-1-weight-loss'
      fullPath: '/products/glp-1-weight-loss'
      preLoaderRoute: typeof ProductsGlp1WeightLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/webhooks': {
      id: '/api/prx/webhooks'
      path: '/api/prx/webhooks'
      fullPath: '/api/prx/webhooks'
      preLoaderRoute: typeof ApiPrxWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/products': {
      id: '/api/prx/products'
      path: '/api/prx/products'
      fullPath: '/api/prx/products'
      preLoaderRoute: typeof ApiPrxProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/patients': {
      id: '/api/prx/patients'
      path: '/api/prx/patients'
      fullPath: '/api/prx/patients'
      preLoaderRoute: typeof ApiPrxPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/orders': {
      id: '/api/prx/orders'
      path: '/api/prx/orders'
      fullPath: '/api/prx/orders'
      preLoaderRoute: typeof ApiPrxOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/me': {
      id: '/api/prx/me'
      path: '/api/prx/me'
      fullPath: '/api/prx/me'
      preLoaderRoute: typeof ApiPrxMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/intake-dynamic': {
      id: '/api/prx/intake-dynamic'
      path: '/api/prx/intake-dynamic'
      fullPath: '/api/prx/intake-dynamic'
      preLoaderRoute: typeof ApiPrxIntakeDynamicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/intake': {
      id: '/api/prx/intake'
      path: '/api/prx/intake'
      fullPath: '/api/prx/intake'
      preLoaderRoute: typeof ApiPrxIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/health': {
      id: '/api/prx/health'
      path: '/api/prx/health'
      fullPath: '/api/prx/health'
      preLoaderRoute: typeof ApiPrxHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/encounters': {
      id: '/api/prx/encounters'
      path: '/api/prx/encounters'
      fullPath: '/api/prx/encounters'
      preLoaderRoute: typeof ApiPrxEncountersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/encounter-types': {
      id: '/api/prx/encounter-types'
      path: '/api/prx/encounter-types'
      fullPath: '/api/prx/encounter-types'
      preLoaderRoute: typeof ApiPrxEncounterTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/checkout': {
      id: '/api/prx/checkout'
      path: '/api/prx/checkout'
      fullPath: '/api/prx/checkout'
      preLoaderRoute: typeof ApiPrxCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/catalog': {
      id: '/api/prx/catalog'
      path: '/api/prx/catalog'
      fullPath: '/api/prx/catalog'
      preLoaderRoute: typeof ApiPrxCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/webhooks/event-types': {
      id: '/api/prx/webhooks/event-types'
      path: '/event-types'
      fullPath: '/api/prx/webhooks/event-types'
      preLoaderRoute: typeof ApiPrxWebhooksEventTypesRouteImport
      parentRoute: typeof ApiPrxWebhooksRoute
    }
    '/api/prx/orders/$orderId': {
      id: '/api/prx/orders/$orderId'
      path: '/$orderId'
      fullPath: '/api/prx/orders/$orderId'
      preLoaderRoute: typeof ApiPrxOrdersOrderIdRouteImport
      parentRoute: typeof ApiPrxOrdersRoute
    }
    '/api/prx/encounters/$encounterId': {
      id: '/api/prx/encounters/$encounterId'
      path: '/$encounterId'
      fullPath: '/api/prx/encounters/$encounterId'
      preLoaderRoute: typeof ApiPrxEncountersEncounterIdRouteImport
      parentRoute: typeof ApiPrxEncountersRoute
    }
    '/api/prx/auth/me': {
      id: '/api/prx/auth/me'
      path: '/api/prx/auth/me'
      fullPath: '/api/prx/auth/me'
      preLoaderRoute: typeof ApiPrxAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prx/encounter-types/$encounterTypeId/schema': {
      id: '/api/prx/encounter-types/$encounterTypeId/schema'
      path: '/$encounterTypeId/schema'
      fullPath: '/api/prx/encounter-types/$encounterTypeId/schema'
      preLoaderRoute: typeof ApiPrxEncounterTypesEncounterTypeIdSchemaRouteImport
      parentRoute: typeof ApiPrxEncounterTypesRoute
    }
  }
}

interface ApiPrxEncounterTypesRouteChildren {
  ApiPrxEncounterTypesEncounterTypeIdSchemaRoute: typeof ApiPrxEncounterTypesEncounterTypeIdSchemaRoute
}

const ApiPrxEncounterTypesRouteChildren: ApiPrxEncounterTypesRouteChildren = {
  ApiPrxEncounterTypesEncounterTypeIdSchemaRoute:
    ApiPrxEncounterTypesEncounterTypeIdSchemaRoute,
}

const ApiPrxEncounterTypesRouteWithChildren =
  ApiPrxEncounterTypesRoute._addFileChildren(ApiPrxEncounterTypesRouteChildren)

interface ApiPrxEncountersRouteChildren {
  ApiPrxEncountersEncounterIdRoute: typeof ApiPrxEncountersEncounterIdRoute
}

const ApiPrxEncountersRouteChildren: ApiPrxEncountersRouteChildren = {
  ApiPrxEncountersEncounterIdRoute: ApiPrxEncountersEncounterIdRoute,
}

const ApiPrxEncountersRouteWithChildren =
  ApiPrxEncountersRoute._addFileChildren(ApiPrxEncountersRouteChildren)

interface ApiPrxOrdersRouteChildren {
  ApiPrxOrdersOrderIdRoute: typeof ApiPrxOrdersOrderIdRoute
}

const ApiPrxOrdersRouteChildren: ApiPrxOrdersRouteChildren = {
  ApiPrxOrdersOrderIdRoute: ApiPrxOrdersOrderIdRoute,
}

const ApiPrxOrdersRouteWithChildren = ApiPrxOrdersRoute._addFileChildren(
  ApiPrxOrdersRouteChildren,
)

interface ApiPrxWebhooksRouteChildren {
  ApiPrxWebhooksEventTypesRoute: typeof ApiPrxWebhooksEventTypesRoute
}

const ApiPrxWebhooksRouteChildren: ApiPrxWebhooksRouteChildren = {
  ApiPrxWebhooksEventTypesRoute: ApiPrxWebhooksEventTypesRoute,
}

const ApiPrxWebhooksRouteWithChildren = ApiPrxWebhooksRoute._addFileChildren(
  ApiPrxWebhooksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  ConfirmationRoute: ConfirmationRoute,
  PrivacyRoute: PrivacyRoute,
  QuizSandboxRoute: QuizSandboxRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsGlp1WeightLossRoute: ProductsGlp1WeightLossRoute,
  AccountIndexRoute: AccountIndexRoute,
  ApiPrxCatalogRoute: ApiPrxCatalogRoute,
  ApiPrxCheckoutRoute: ApiPrxCheckoutRoute,
  ApiPrxEncounterTypesRoute: ApiPrxEncounterTypesRouteWithChildren,
  ApiPrxEncountersRoute: ApiPrxEncountersRouteWithChildren,
  ApiPrxHealthRoute: ApiPrxHealthRoute,
  ApiPrxIntakeRoute: ApiPrxIntakeRoute,
  ApiPrxIntakeDynamicRoute: ApiPrxIntakeDynamicRoute,
  ApiPrxMeRoute: ApiPrxMeRoute,
  ApiPrxOrdersRoute: ApiPrxOrdersRouteWithChildren,
  ApiPrxPatientsRoute: ApiPrxPatientsRoute,
  ApiPrxProductsRoute: ApiPrxProductsRoute,
  ApiPrxWebhooksRoute: ApiPrxWebhooksRouteWithChildren,
  ApiPrxAuthMeRoute: ApiPrxAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
