/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ProductsTrtHormonalRouteImport } from './routes/products/trt-hormonal'
import { Route as ProductsPerformanceRecoveryRouteImport } from './routes/products/performance-recovery'
import { Route as ProductsLongevityPeptidesRouteImport } from './routes/products/longevity-peptides'
import { Route as ProductsGlp1WeightLossRouteImport } from './routes/products/glp-1-weight-loss'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsTrtHormonalRoute = ProductsTrtHormonalRouteImport.update({
  id: '/products/trt-hormonal',
  path: '/products/trt-hormonal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPerformanceRecoveryRoute =
  ProductsPerformanceRecoveryRouteImport.update({
    id: '/products/performance-recovery',
    path: '/products/performance-recovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsLongevityPeptidesRoute =
  ProductsLongevityPeptidesRouteImport.update({
    id: '/products/longevity-peptides',
    path: '/products/longevity-peptides',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsGlp1WeightLossRoute = ProductsGlp1WeightLossRouteImport.update({
  id: '/products/glp-1-weight-loss',
  path: '/products/glp-1-weight-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/quiz': typeof QuizRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/glp-1-weight-loss': typeof ProductsGlp1WeightLossRoute
  '/products/longevity-peptides': typeof ProductsLongevityPeptidesRoute
  '/products/performance-recovery': typeof ProductsPerformanceRecoveryRoute
  '/products/trt-hormonal': typeof ProductsTrtHormonalRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/quiz': typeof QuizRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/glp-1-weight-loss': typeof ProductsGlp1WeightLossRoute
  '/products/longevity-peptides': typeof ProductsLongevityPeptidesRoute
  '/products/performance-recovery': typeof ProductsPerformanceRecoveryRoute
  '/products/trt-hormonal': typeof ProductsTrtHormonalRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/confirmation': typeof ConfirmationRoute
  '/quiz': typeof QuizRoute
  '/category/$slug': typeof CategorySlugRoute
  '/products/glp-1-weight-loss': typeof ProductsGlp1WeightLossRoute
  '/products/longevity-peptides': typeof ProductsLongevityPeptidesRoute
  '/products/performance-recovery': typeof ProductsPerformanceRecoveryRoute
  '/products/trt-hormonal': typeof ProductsTrtHormonalRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/confirmation'
    | '/quiz'
    | '/category/$slug'
    | '/products/glp-1-weight-loss'
    | '/products/longevity-peptides'
    | '/products/performance-recovery'
    | '/products/trt-hormonal'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/confirmation'
    | '/quiz'
    | '/category/$slug'
    | '/products/glp-1-weight-loss'
    | '/products/longevity-peptides'
    | '/products/performance-recovery'
    | '/products/trt-hormonal'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/confirmation'
    | '/quiz'
    | '/category/$slug'
    | '/products/glp-1-weight-loss'
    | '/products/longevity-peptides'
    | '/products/performance-recovery'
    | '/products/trt-hormonal'
    | '/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfirmationRoute: typeof ConfirmationRoute
  QuizRoute: typeof QuizRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductsGlp1WeightLossRoute: typeof ProductsGlp1WeightLossRoute
  ProductsLongevityPeptidesRoute: typeof ProductsLongevityPeptidesRoute
  ProductsPerformanceRecoveryRoute: typeof ProductsPerformanceRecoveryRoute
  ProductsTrtHormonalRoute: typeof ProductsTrtHormonalRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/trt-hormonal': {
      id: '/products/trt-hormonal'
      path: '/products/trt-hormonal'
      fullPath: '/products/trt-hormonal'
      preLoaderRoute: typeof ProductsTrtHormonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/performance-recovery': {
      id: '/products/performance-recovery'
      path: '/products/performance-recovery'
      fullPath: '/products/performance-recovery'
      preLoaderRoute: typeof ProductsPerformanceRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/longevity-peptides': {
      id: '/products/longevity-peptides'
      path: '/products/longevity-peptides'
      fullPath: '/products/longevity-peptides'
      preLoaderRoute: typeof ProductsLongevityPeptidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/glp-1-weight-loss': {
      id: '/products/glp-1-weight-loss'
      path: '/products/glp-1-weight-loss'
      fullPath: '/products/glp-1-weight-loss'
      preLoaderRoute: typeof ProductsGlp1WeightLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ConfirmationRoute: ConfirmationRoute,
  QuizRoute: QuizRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductsGlp1WeightLossRoute: ProductsGlp1WeightLossRoute,
  ProductsLongevityPeptidesRoute: ProductsLongevityPeptidesRoute,
  ProductsPerformanceRecoveryRoute: ProductsPerformanceRecoveryRoute,
  ProductsTrtHormonalRoute: ProductsTrtHormonalRoute,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
